### ISSUE TITLE
Plugin does not load and raises error

### ISSUE THREAD

**Issue by FurloSK** [ethz-let/moodle-filter_threedviewer#2]
I was unable to make the plugin actually replace the links. I tried both ways (simple ```<a>``` tag and ```<threed-viewer>``` custom element), but to no success. Also, when the plugin is activated and I go to a page activity where some STL model is added, Chrome console shows one error which otherwise (i.e. when the plugin is disabled) is not displayed: 
```
https://MYSITE/lib/requirejs.php/1667205363/core/first.js line 250:
Uncaught ReferenceError: regeneratorRuntime is not defined
    at first.js:250:16479
    at first.js:250:16874
    at Object.execCb (require.min.js:1:12861)
    at b.check (require.min.js:1:6615)
    at b.enable (require.min.js:1:9363)
    at Object.enable (require.min.js:1:11918)
    at b.<anonymous> (require.min.js:1:9220)
    at require.min.js:1:814
    at each (require.min.js:1:289)
    at b.enable (require.min.js:1:8720)
```
I tried purging all the site caches, disabling all the other filters and also double-checked that this error is not shown when the plugin is disabled.

Any thoughts what might be the problem? Or how to proceed?

**Comment by nexterday** [comment]
Hi, to have a better understanding of the issue, could you please disable (untick) "Cache Javascript" from /admin/settings.php?section=ajax and see if it works? the specific error above indicates a problem in Babel eslint; so either our transpiled amd files are not being grunted correct (or within correct env) or simply you have an issue within your grunt files (moodle core).

Please report back when you disable/untick "Cache Javascript"

**Comment by cyrilpic** [comment]
Just to add to the previous comment: the links are replaced by the Javascript part of the filter. So, if there is a Javascript error, the viewer will not be displayed.

Also, what version of Moodle are you trying to run it on?

**Comment by ArslanKathia** [comment]
The plugin is working fine and loads successfully gltf file...
Something to make sure which is correct in most important is the src URL... when you place the model inside the Moodle directory you just have to provide the folder path in which you placed the file..
Like src="/3d/scene.gltf" so the root path Moodle automatically added and loaded the resource...
